language: r
sudo: false
cache: packages

r_packages:
 - devtools

r_github_packages:
 - rqtl/qtl2geno

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: always
